1012 proxy coverage
hashgraph/hedera-smart-contracts pull request #1125
Opened 2024-12-20 12:24 UTC by simzzz

**Description**:
This PR adds test coverage for the HRC904Proxy contract and its functions as per the [design doc](https://github.com/hashgraph/hedera-services/blob/v0.57.2/hedera-node/docs/design/services/smart-contract-service/frictionless-airdrops-system-contracts.md).

**Related issue(s)**:
(not yet open)
Fixes #

**Notes for reviewer**:
This PR is still incomplete and has some redundancy with #1124 as I am reusing some of the files and managing multiple PR's isn't as straight forward when using a fork. To-do items added in the checklist below

**Checklist**

- [ ] Figure out a way to assert the child transactions (most time consuming so far)
- [ ] Polish code and fix assertions to use the right status codes and messages

2025-01-07 07:13 UTC, Nana-EC commented on .github/workflows/manual-testing.yml
> +      enableTmate: true
Q: why do we need this and where is it utilized?

2025-01-08 17:01 UTC, Nana-EC reviewed
Nice work, some tweaks and then let's get this in

2025-01-08 17:01 UTC, Nana-EC commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/TokenReject.sol
> +contract TokenReject is HederaTokenService {
Curious, why the separation from HRC904Contract.sol?

2025-01-08 17:01 UTC, Nana-EC commented on test/constants.js
> +const PRECOMPILE_ADDRESS = '0.0.359';
```suggestion
const HTS_SYSTEM_CONTRACT_ADDRESS = '0.0.359';
```

2025-01-09 08:46 UTC, simzzz commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/TokenReject.sol
> +contract TokenReject is HederaTokenService {
Some of the subtasks on the epic state "Add tests that verify IHRC904 rejectTokens targeted to an EOA are functional when called by a contract". This is the example contract I planned to use to cover the test cases and it also allows me to do a batch reject.

2025-01-10 04:41 UTC, Nana-EC approved these changes
LG

2025-01-10 22:26 UTC, acuarica approved these changes

2025-01-10 22:26 UTC, acuarica commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol
> +    event IsAssociated(bool status);
where is this event used?

2025-01-11 00:24 UTC, quiet-node reviewed
Nice process. I have other idea for the PR tho.

Given the urgent priority of pushing the example contracts for Frictionless Airdrop, I suggest repurposing this PR to focus solely on `feat: adds example HRC904 contracts.`

The test coverage for the AirdropContract can be moved to a separate PR, as I believe it would need additional work on it. This approach is preferable since other contracts, such as CancelAirdrop and ClaimAirdrop, also need test coverage.

Additionally, we would also have these tests running in CI for better visibility as well. And in order to run these tests in CI it would require extra work, including adding a new workflow and updating local-node to use the correct network version. 

For now, limiting this PR to the example contracts seems like the best appraoch I believe.

2025-01-11 00:24 UTC, quiet-node commented on test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
> +    expect(responseCode).to.eq('178'); // INSUFFICIENT_TOKEN_BALANCE code
Ah this is nice!

2025-01-11 00:24 UTC, quiet-node commented on test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
> +  it('should fail when 11 or more NFT airdrops are provided', async function () {
Nice I didn't know the tokenTransferList on accept up to 10 items as stated in the desgin doc at this section https://github.com/hashgraph/hedera-services/blob/v0.57.2/hedera-node/docs/design/services/smart-contract-service/frictionless-airdrops-system-contracts.md#input-limitations. Hmmm we shouldd add this information in the IHRC904 contracts or any where that's applicable so the users would know it only accept 10 items only.

2025-01-11 00:24 UTC, quiet-node commented on test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
> +    await txNFT2.wait();
Just go through the test suite and didn't see any coverage for nftAirdropDistribute()

2025-01-13 09:15 UTC, simzzz commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/Airdrop.sol
> +        }
`receivers.length` is uint256, I felt like a for loop would be cleaner than type conversions in this case

2025-01-13 09:28 UTC, simzzz commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol
> +    }
I wanted to use them for utility for the proxy method tests, but on a second thought I can just deploy HRC719 contract there to avoid redundancy. Removing them

2025-01-13 17:38 UTC, quiet-node commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/Airdrop.sol
> +        }
Got it! You’re right type casting can be tricky and prone to errors at times. Thanks for pointing that out!

2025-01-13 17:42 UTC, quiet-node commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol
> +pragma experimental ABIEncoderV2;
QQ: What is this for again?

2025-01-13 17:42 UTC, quiet-node commented on test/constants.js
> +  Airdrop: 'Airdrop',
Hmm, if we’ve already repurposed the PR, let’s move the changes in the test/ folder to the upcoming PRs along with the test coverage.

2025-01-14 11:55 UTC, simzzz commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol
> +pragma experimental ABIEncoderV2;
Since we support a wide range of versions 'pragma solidity >=0.5.0 <0.9.0;' if somebody were to use this contract with an older version, some methods in the contract might break. I noticed it's common in other contracts as well.

2025-01-14 16:18 UTC, quiet-node commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol
> +pragma experimental ABIEncoderV2;
Nice thanks for the explanation!

2025-01-14 16:21 UTC, quiet-node approved these changes
LGTM! Great work!

2025-01-15 11:07 UTC, konstantinabl submitted a review, later dismissed

2025-01-15 11:07 UTC, konstantinabl commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/Airdrop.sol
> +    function prepareAA(address sender, address receiver, int64 amount) internal pure returns (IHederaTokenService.AccountAmount[] memory transfers) {
Can you rename this method. PrepareAA doesn't give much info

2025-01-15 11:07 UTC, konstantinabl commented on artifacts/contracts/system-contracts/hedera-token-service/examples/token-query/TokenQueryContract.sol/TokenQueryContract.json
> -  "bytecode": "0x608060405234801561000f575f80fd5b50600160208181527fa6eef7e35abe7026729641147f7915573c7e97b47efa546f5f6e3230263bcb499190915560027fcc69885fda6bcc1a4ace058b4a62bf5e179ea78fd58a1ccd71c22c
Why is this changed in this PR, I think you havent changed anything to the TokenQueryContract here? Same goes to the TokenManagementContract and TokenTransferContract

2025-01-15 11:09 UTC, konstantinabl requested changes
Left some comments

2025-01-15 11:12 UTC, simzzz commented on contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol
> +    event IsAssociated(bool status);
it was leftover from earlier logic, I removed it

2025-01-15 11:57 UTC, konstantinabl approved these changes

2025-01-15 16:01 UTC, quiet-node commented on artifacts/contracts/system-contracts/hedera-token-service/examples/token-query/TokenQueryContract.sol/TokenQueryContract.json
> -  "bytecode": "0x608060405234801561000f575f80fd5b50600160208181527fa6eef7e35abe7026729641147f7915573c7e97b47efa546f5f6e3230263bcb499190915560027fcc69885fda6bcc1a4ace058b4a62bf5e179ea78fd58a1ccd71c22c
Those contracts are inherited by the HederaTokenService and with new additions to the HederaTokenService contracts resulting in updated bytecode.

2025-01-16 14:53 UTC, konstantinabl commented on test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
> +    await txNFT2.wait();
@simzzz have you discussed this with @quiet-node 
its not resolved so not sure

2025-01-16 14:55 UTC, simzzz commented on test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
> +    await txNFT2.wait();
Yes, we agreed to move the test coverage to a separate PR where I will address the rest of the comments. Resolving  here

2025-01-16 15:50 UTC, merged