Refactor constants
hashgraph/hedera-smart-contracts pull request #209
Opened 2023-04-11 07:01 UTC by attest08

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-04-11 07:44 UTC, yiliev0 commented on test/constants.js
> +    Success: "success",
The following keys appear more than once in the object:

ResponseCode
Frozen
KycGranted
TokenExpiryInfo
TokenInfo
TokenKey
FungibleTokenInfo

2023-04-12 23:01 UTC, Nana-EC requested changes
Nice improvement.
Some requests

2023-04-12 23:01 UTC, Nana-EC commented on test/constants.js
> +}
Same for `diamond.helper.js`

2023-04-12 23:01 UTC, Nana-EC commented on test/constants.js
> +const Events = {
Missing License header.
See the text in existing files.
Should be added to all new files

2023-04-15 02:20 UTC, Nana-EC commented on test/constants.js
> + * Copyright (C) 2022 Hedera Hashgraph, LLC
```suggestion
 * Copyright (C) 2023 Hedera Hashgraph, LLC
```

2023-04-15 02:20 UTC, Nana-EC commented on test/diamond-pattern/diamond.helper.js
> +let DiamondHelper = {
missing license header

2023-04-19 14:21 UTC, georgi-l95 submitted a review, later dismissed
LG

2023-04-20 15:06 UTC, Nana-EC submitted a review, later dismissed
LG

2023-04-21 04:51 UTC, Nana-EC commented
@attest08 you have to sign the commits

2023-04-21 08:30 UTC, georgi-l95 submitted a review, later dismissed

2023-04-21 08:35 UTC, natanasow approved these changes
LGTM

2023-04-21 09:04 UTC, georgi-l95 approved these changes

2023-04-21 10:55 UTC, merged