tests: add documentation for test automation #229
hashgraph/hedera-smart-contracts pull request #239
Opened 2023-05-17 14:31 UTC by attest08

**Related issue(s)**:

Fixes #229 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-17 14:39 UTC, natanasow submitted a review, later dismissed

2023-05-18 02:05 UTC, Nana-EC requested changes
Nice. Some suggestions

2023-05-18 02:05 UTC, Nana-EC commented on test/README.md
> +![launch.json](/../hedera-smart-contracts/launch.png)
Move to subfolder `./test/images` for now
```suggestion
![launch.json](/../hedera-smart-contracts/test/images/launch.png)
```

2023-05-18 02:05 UTC, Nana-EC commented on test/README.md
> +3. Run in the terminal "npx hardhat test"
Q: is there not a way to filter tests by file through command line?
That would be better if possible than devs having to change code

2023-05-18 02:05 UTC, Nana-EC commented on test/README.md
> +# Hedera Smart Contracts - tests
Add a link to this README in the root README

2023-05-18 17:16 UTC, Nana-EC approved these changes

2023-05-19 05:26 UTC, merged