Add Allowance/Approval methods to HTS precompile
hashgraph/hedera-smart-contracts pull request #29
Opened 2022-06-29 21:39 UTC by shemnon

**Description**:
Add the missing Allowance/Approval methods that can be accessed via
the ERC-20 proxy that is not available in the HTS precompile.

**Related issue(s)**:

Fixes #6

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-29 21:52 UTC, Nana-EC requested changes
Looks good.
If you don't mind can you add some nits that clarify account is account address ~and what unit the amounts are~.
It may or may not be clear depending on familiarity with Hedera and which side you're coming from so better to be explicit

2022-06-29 21:52 UTC, Nana-EC commented on hts-precompile/IHederaTokenService.sol
> +    /// @param amount the amount of tokens authorized to spend.
nit: can we add the unit for this and other amounts. Devs may not know if its a gas unit or an hbar unit

2022-06-29 21:52 UTC, Nana-EC commented on hts-precompile/HederaTokenService.sol
> +
nit: extra line

2022-06-29 22:19 UTC, Nana-EC commented on hts-precompile/IHederaTokenService.sol
> +    /// @param amount the amount of tokens authorized to spend.
Ignore. Mixed items up

2022-06-30 00:32 UTC, Nana-EC submitted a review, later dismissed
Unblocking since now just nits

2022-06-30 01:53 UTC, shemnon commented on hts-precompile/HederaTokenService.sol
> +
done

2022-06-30 01:57 UTC, Nana-EC approved these changes

2022-06-30 02:00 UTC, merged