Added an part 1 of an example for transferring HBAR to a contract
hashgraph/hedera-smart-contracts pull request #37
Opened 2022-07-20 20:25 UTC by ed-marquez

**Description**:

**Checklist**
- [x] Documented (Code comments, article in hedera.com/blog)
- [x] Tested

2022-07-31 01:09 UTC, Nana-EC requested changes
Thanks for the example.
Debating whether this repo or sdk-js is the best location.
For now it's okay.

Also may want to consider the following
- making it a complete npm package that's easy to run
- adding a README

2022-07-31 01:09 UTC, Nana-EC commented on examples/transfer-hbar2contracts-sdk/transferHbar2Contract_sdk.js
> +	const contractBytecode = fs.readFileSync("transferHbar2Contract_sdk_sol_hbar2Contract.bin");
nit: folder already gives context
```suggestion
	const contractBytecode = fs.readFileSync("hbar2Contract.bin");
```

2022-07-31 01:09 UTC, Nana-EC commented on examples/transfer-hbar2contracts-sdk/transferHbar2Contract_sdk.js
> +		`\n- Created Alice's account with initial balance of ${initialBalance} hbar: ${accStatus}`
```suggestion
		`\n- Created Alice's account '${aliceId}' with initial balance of ${initialBalance} hbar: ${accStatus}`
```

2022-08-15 20:48 UTC, ed-marquez commented
Addressed the changes suggested and rebased the branched to conform to DCO checks.

2022-08-17 01:22 UTC, SimiHunjan approved these changes

2022-08-19 17:01 UTC, closed without merging

2022-08-19 17:02 UTC, ed-marquez commented
Closing this merge requests for now. I just added another examples for a 2nd part of the article. Will create a new requests that includes both examples