Adding tests for Arithmetic
hashgraph/hedera-smart-contracts pull request #481
Opened 2023-10-17 13:59 UTC by stefan-stefanooov

**Description**:
Adding tests for Arithmetic

**Related issue(s)**:
https://github.com/hashgraph/hedera-smart-contracts/issues/473

2023-10-17 15:34 UTC, natanasow requested changes
Some improvements IMO, @Nana-EC what do you think about that?

2023-10-17 15:34 UTC, natanasow commented on test/solidity/cryptomath/arithmetic.js
> +    it('it should confirm solidity functionality: Arithmetic, checked overflow - confirm revert add2', async function () {
same as above and all other tests below

2023-10-17 15:34 UTC, natanasow commented on contracts/solidity/cryptomath/Arithmetic.sol
> +        return true;
the return statement could be removed if we don't use it

2023-10-17 16:22 UTC, Nana-EC commented on test/solidity/cryptomath/arithmetic.js
> +    });
Agreed

2023-10-19 15:42 UTC, Nana-EC submitted a review, later dismissed

2023-10-19 17:09 UTC, stefan-stefanooov commented
@Nana-EC  please look at the `utils/helpers.js` changes.
I think they are needed. And they were breaking the tests constantly

2023-10-19 21:24 UTC, Nana-EC approved these changes

2023-10-20 06:42 UTC, natanasow approved these changes

2023-10-20 06:44 UTC, merged