Аdds oz beacon proxy tests
hashgraph/hedera-smart-contracts pull request #604
Opened 2023-11-21 17:22 UTC by konstantinabl

**Description**:

This PR adds test for the beacon proxy OZ contracts 
**Related issue(s)**:

Fixes #599

2023-11-22 17:02 UTC, quiet-node requested changes
LG but some comments

2023-11-22 17:02 UTC, quiet-node commented on test/beacon-proxy/beaconProxy.js
> +/*-
Please move this folder into `test/solitiy/oz/` folder

2023-11-22 17:02 UTC, quiet-node commented on test/solidity/oz/transparent-upgradeable-proxy/transparentProxy.js
> +/*-
duplicated

2023-11-28 15:43 UTC, konstantinabl commented on contracts/solidity/oz/TransparentUpgradeableProxy/Box.sol
> +contract Box {
I rebase onto upgradeable proxy branch cause i needed some changes. Fixed now

2023-11-30 19:17 UTC, quiet-node approved these changes
LGTM

2023-12-01 09:02 UTC, georgi-l95 approved these changes
👁️ 👍 👉 👨‍💻

2023-12-04 14:13 UTC, merged