539 OZ Access control example
hashgraph/hedera-smart-contracts pull request #609
Opened 2023-11-24 20:00 UTC by ebadiere

OpenZeppelin Access control example.

**Related issue(s)**:

Fixes #539

2023-12-08 03:44 UTC, quiet-node requested changes
LG but still need some changes

2023-12-08 03:44 UTC, quiet-node commented on test/OZ/access-control/accessControl.js
> +// Import Hardhat and Ethereum assertion libraries
Missing comment header

2023-12-08 03:44 UTC, quiet-node commented on test/OZ/access-control/accessControl.js
> +describe("@OZTokenValut AccessControlContract", function () {
Please update the tag

2023-12-08 03:44 UTC, quiet-node commented
Also the PR title check is failing please update the PR title

2023-12-11 16:58 UTC, ebadiere commented on test/OZ/access-control/accessControl.js
> +describe("@OZTokenValut AccessControlContract", function () {
Done.

2023-12-11 18:16 UTC, ebadiere commented
> Also the PR title check is failing please update the PR title

Done.

2023-12-11 18:55 UTC, quiet-node submitted a review, later dismissed
LG 1 nit

2023-12-11 18:55 UTC, quiet-node commented on test/OZ/access-control/accessControl.js
> +describe("@OZ AccessControlContract", function () {
nit: should be @OZAccessControlContract

2023-12-11 20:03 UTC, ebadiere commented on test/OZ/access-control/accessControl.js
> +describe("@OZ AccessControlContract", function () {
Done.

2023-12-12 01:21 UTC, quiet-node approved these changes
LG

2023-12-12 02:55 UTC, merged