Add ERC 20 example contract to highlight HIP 218
hashgraph/hedera-smart-contracts pull request #72
Opened 2022-09-27 10:39 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #32

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-09-28 13:55 UTC, Nana-EC requested changes
Looks good, just needs the tests coverage setup using hardhat and local node

2022-09-28 13:55 UTC, Nana-EC commented on contracts/hts-precompile/ERC20Contract.sol
> +contract ERC20Contract {
Looks good.
Please wait on https://github.com/hashgraph/hedera-smart-contracts/pull/57 to go in and then add test coverage for at least the `name`, `symbol`, `decimals` and `totalSupply` methods.

Reminder the goal would be the initial coverage we added in the relay would not be needed and this repo would be the source of basic and simple contracts with their tests using hardhat and local-node.
Nothing complex, just easy to view and run from a pure web3 (less Hedera) point of view

2022-09-29 21:33 UTC, shemnon commented
I would move this to the examples directory, based on the tag line of the PR.

2022-09-30 02:30 UTC, Nana-EC commented
> Reference
Yeah #74 might have to go in first to provide the folder structure

2022-09-30 19:12 UTC, Nana-EC reviewed
Looks good, just need to move ERC20Contract.sol into it's own dir under `contrcts/hts-precompile/examples`

2022-09-30 19:12 UTC, Nana-EC commented on contracts/hts-precompile/ERC20Contract.sol
> +contract ERC20Contract {
To Danno's point this should be under examples
Place it under `contracts/hts-precompile/examples` in an `erc20` dir

2022-10-04 21:15 UTC, shemnon commented
Files should be in a location with "example" as a directory in the path.

2022-10-05 00:23 UTC, Nana-EC approved these changes
LG

2022-10-05 04:48 UTC, merged