Cleanup hts-precompile
hashgraph/hedera-smart-contracts pull request #83
Opened 2022-10-05 19:34 UTC by bgok

Clean up dependencies of hts-precompile modules to reduce unnecessary coupling and fix some warnings about visibility modifiers.

**Description**:
The PR modifies the ht-precompile contracts to:
* Reduce coupling between helpers
* Changes HederaResponseCodes to a library
* Makes all hts-precompile contracts abstract
* Changes the visibility of FeeHelper to pure to silence compiler warnings.

**Related issue(s)**:
None

**Notes for reviewer**:
There are some broken unit tests in the IERC20 directory that are broken, so this change probably won't pass CI.

**Checklist**

- [n/a] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-10-07 18:21 UTC, Nana-EC commented
Hi @bgok 

Thanks for the PR, appreciate the improvement suggestions.
We'll take a look.

In the mean time please review the [Contribution guidelines](https://github.com/hashgraph/hedera-smart-contracts#contributing) and the linked organization doc.

2022-10-13 15:48 UTC, georgi-l95 requested changes
LG, should fix test errors.

2022-10-27 16:48 UTC, Nana-EC commented
@bgok ping on this.
When do you think you'd be able to address the feedback so we can progress this along.

2022-10-28 16:20 UTC, Nana-EC commented
@bgok we'll take this over next week if we don't hear back or if you're unable to address the feedback in time.
Thanks for the initial change suggestions

2022-10-28 19:59 UTC, bgok commented
The CI error existed in the main branch prior to my fork. See https://github.com/hashgraph/hedera-smart-contracts/commit/c61cc9f958bfa1721045a9426670e51b04a5f9b9.

I've been pulled from the project this change was needed for. I'll try a quick rebase to see if that fixes the CI error. If it doesn't, I'll close this PR.

2022-11-03 09:49 UTC, georgi-l95 commented
Opened new [PR](https://github.com/hashgraph/hedera-smart-contracts/pull/126) to resolve this.

2022-11-03 09:49 UTC, closed without merging